services:
    mongo-db:
        container_name: mongoDB
        image: mongo
        restart: "${RESTART_POLICY:-no}"
        healthcheck:
            test: ["CMD", "echo", "'db.runCommand(\"ping\").ok'", "|", "mongosh", "localhost:27017/test", "--quiet"]
            interval: 10s
            timeout: 10s
            retries: 5
            start_period: 40s
        environment:
            # These *INITDB* variables only used when the database is first initialized
            MONGO_INITDB_ROOT_USERNAME: "${MONGO_USERNAME:-admin}"
            MONGO_INITDB_ROOT_PASSWORD: "${MONGO_PASSWORD:-super-not-secure}"
        volumes:
            - type: bind
              source: ./mongo
              target: /data/db
        # open a port on the localhost computer for using the API outside a docker container
        ports: ["27017:27017"]
        profiles: ["db"]
        networks:
            - hynet

    web-to-py:
        build:
            context: ./web2py
        pull_policy: always
        restart: "${RESTART_POLICY:-no}"
        environment:
            BASE_API_URL: "http://django-api:8111"
        read_only: "${READ_ONLY:-false}"
        volumes:
            # uncomment below to sync all the web2py files for development
            # - ./web2py:/home/web2py/web2py:rw
            # store log and other files in a volume on the host
            - "web_to_py_temp:/home/python_kid/web2py_app/temp_data:rw"
            # gunicorn to store temporary files
            - "web_to_py_gunicorn_tmp:/var/tmp:rw"
            # session data (saved user session states)
            - "web_to_py_session_data:/home/python_kid/web2py_app/applications/hypatia/sessions:rw"

        # the first command to run when the container starts, start the gunicorn server
        command: ["python", "anyserver.py", "-s", "gunicorn", "-i", "0.0.0.0", "-p", "8222"]
        # ports: ["8222:8222"]
        profiles: ["dual"]
        networks:
            - hynet

    django-api:
        build: ./backend
        restart: "${RESTART_POLICY:-no}"
        # ports: ["8111:8111"]
        environment:
            DJANGO_SECRET_KEY: "${DJANGO_SECRET_KEY}"
            MONGO_USERNAME: "${MONGO_USERNAME:-admin}"
            MONGO_PASSWORD: "${MONGO_PASSWORD:-super-not-secure}"
            MONGO_HOST: "${MONGO_HOST:-mongoDB}"
            MONGO_DATABASE: "${MONGO_DATABASE:-test}"
            MONGO_STARNAMES_COLLECTION: "${MONGO_STARNAMES_COLLECTION:-stars}"
            INTERACTIVE_STARNAMES: "{INTERACTIVE_STARNAMES:-true}"
        read_only: "${READ_ONLY:-false}"
        volumes:
            # django_static is written at build time by the SpExWebsite Dockerfile
            - "django_static:/app/static_root:ro"
            # matplotlib_cache is recommended for matplotlib to work in a docker container
            - "matplotlib_cache:/home/python_user/django_backend/.cache/matplotlib:rw"
            # gunicorn to store temporary files
            - "gunicorn_tmp:/var/tmp:rw"
            # Data input for processing
            - "./backend/hypatia/HyData:/home/python_user/django_backend/hypatia/HyData:${VOLUME_SPECIFICATION:-rw}"
            # Data output from processing
            - "./backend/output:${DATA_OUTPUT_DIR:-/home/python_user/django_backend/output}:${VOLUME_SPECIFICATION:-rw}"
        command: ["gunicorn", "core.wsgi", "--bind", "0.0.0.0:8111"]
        profiles: ["dual", "api"]
        networks:
            - hynet

    ipython:
        container_name: ipython
        build:
            context: ./backend
            dockerfile: ipython.Dockerfile
        restart: "${RESTART_POLICY:-no}"
        user: root
        ports:
            - "8888:8888"
        environment:
            JUPYTER_TOKEN: "${JUPYTER_TOKEN:-docker}"
            GRANT_SUDO: "yes"
            DOCKER_STACKS_JUPYTER_CMD: "notebook"
            DJANGO_SECRET_KEY: "${DJANGO_SECRET_KEY}"
            MONGO_USERNAME: "${MONGO_USERNAME:-admin}"
            MONGO_PASSWORD: "${MONGO_PASSWORD:-super-not-secure}"
            MONGO_HOST: "${MONGO_HOST:-mongoDB}"
            MONGO_STARNAMES_COLLECTION: "${MONGO_STARNAMES_COLLECTION:-stars}"
            CONNECTION_STRING: ${CONNECTION_STRING:-none}
            INTERACTIVE_STARNAMES: "{INTERACTIVE_STARNAMES:-true}"
        volumes:
            - ./backend:/backend
        profiles: ["ipython"]
        networks:
            - hynet

    nginx-hysite:
        container_name: nginx-hysite
        image: nginx:latest
        restart: "${RESTART_POLICY:-no}"
        ports:
            - "${LOCAL_PORT:-80}:80"
        volumes:
            - "./nginx/default.conf:/etc/nginx/conf.d/default.conf"
            - "django_static:/django/static_root:ro"
        profiles: ["dual", "api"]
        networks:
            - hynet

volumes:
    django_static:
    matplotlib_cache:
    gunicorn_tmp:
    web_to_py_temp:
    web_to_py_gunicorn_tmp:
    web_to_py_session_data:

networks:
    hynet:
        name: hynet
        external: "${USE_EXTERNAL_NETWORK:-false}"