import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import React, {ReactElement} from "react";
import Script from 'next/script'

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export function QueryClient(): ReactElement {
    return (
        <div className="flex flex-col h-full w-full absolute top-0 left-0 z-10">
            <div className="flex-none w-full items-center font-mono text-lg p-4">
                <div>
                    <div className="flex flex-row gap-4">
                        <div>
                            Home
                        </div>
                        <div>
                            Elements & Properties
                        </div>
                        <div>
                            Stars With/Without Planets
                        </div>
                    </div>
                </div>
            </div>
        </div>
    );
}


export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <head>
            <title>Spectroscopy of Exoplanet-forming Disks</title>
            <Script src="https://www.googletagmanager.com/gtag/js?id=G-TNXP7EHWXV"/>
            <Script id="google-analytics">
                {`
                  window.dataLayer = window.dataLayer || [];
                  function gtag() {dataLayer.push(arguments)}
                  gtag('js', new Date());
                  gtag('config', 'G-TNXP7EHWXV');
                `}
            </Script>
        </head>
        <body className={inter.className}>
            <main className="flex min-h-screen flex-col items-center justify-between p-24">
                <QueryClient/>
                {children}
            </main>
        </body>
        </html>
);
}
