net:
  port: 27017
  bindIp: 0.0.0.0
  tls:
    mode: allowTLS
    certificateKeyFile: "/etc/letsencrypt/mongo-ssl/mongodb.pem"
    CAFile: "/etc/letsencrypt/mongo-ssl/fullchain.pem"
    allowConnectionsWithoutCertificates: true