net:
  port: 27017
  bindIp: 0.0.0.0
  tls:
    mode: requireTLS
    certificateKeyFile: "/etc/letsencrypt/live/hypatiacatalog.com/mongodb.pem"
    CAFile: "/etc/letsencrypt/live/hypatiacatalog.com/fullchain.pem"